// <auto-generated />
namespace Financeiro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TabelasIniciais : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabelasIniciais));
        
        string IMigrationMetadata.Id
        {
            get { return "201609080002293_TabelasIniciais"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
